FROM --platform=$BUILDPLATFORM node:16.8.0 AS builder
ARG TARGET_BRANCH=release-1.6.0

RUN apt-get install -y git
RUN git clone https://github.com/IBM/ibm-storage-odf-console.git
WORKDIR /ibm-storage-odf-console
RUN git fetch origin ${TARGET_BRANCH} && git checkout origin/${TARGET_BRANCH}

RUN yarn install --prod=false
RUN yarn build
RUN mv ./dist ../app

RUN git fetch origin ${TARGET_BRANCH} && git checkout origin/${TARGET_BRANCH}
RUN yarn install
RUN yarn build
RUN mv ./dist ../compatibility

FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi8/nginx-124
ADD default.conf "${NGINX_CONFIGURATION_PATH}"
COPY --from=builder /app .
COPY --from=builder /compatibility ./compatibility
CMD /usr/libexec/s2i/run

LABEL maintainer="IBM Support <support@ibm.com>"
LABEL name="ibm-storage-odf-console"
LABEL version="1.6.0"
LABEL description="IBM Flashsystem Console Plugin"
LABEL summary="Provides the IBM flashsystem console for OpenShift Data Foundation."
LABEL io.k8s.display-name="IBM Flashsystem Console"
LABEL io.openshift.tags="odf"
