name: codespell

on: workflow_dispatch

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: codespell
      uses: crate-ci/typos@master
