name: iso-ci.yaml

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [ published ]

jobs:
  precheck-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
      with:
        fetch-depth: 0

    - name: check copyright
      run: |
        ./hack/check-copyright.sh

    - name: login to Quay.io
      # Only if we need to push an image
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAYIO_USERNAME }}
        password: ${{ secrets.QUAYIO_TOKEN }}

    # Setup for buildx
    - name: set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Debugging information
    - name: docker info
      run: docker info
    - name: buildx inspect
      run: docker buildx inspect
    
    - name: get tag without v
      id: tag
      shell: bash
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      run: |
        VERSION=${{ github.event.release.tag_name }}
        echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

    # Build and (optionally) push the plugin image
    - name: build the plugin image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.prod
        platforms: linux/amd64,linux/ppc64le,linux/s390x
        #build-args: |
        #  TARGET_BRANCH=${{ github.head_ref || github.ref_name }}
        # Only push if we are publishing a release
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        # Use a 'dev' tag, that won't be pushed, for non-release builds
        tags: quay.io/ibmodffs/ibm-storage-odf-plugin:${{ needs.tag.outputs.version || 'dev' }}
